name: License Check

on: 
  workflow_call:
  
jobs:
  License-Check:
    runs-on: ubuntu-latest
    
    services:
      fossology:
        image: fossology/fossology:3.10.0
        ports:
        - 8081:80
    
    steps:
      - name: Get license engine
        uses: actions/checkout@v3
        with:
            repository: OpenTOSCA/license-engine

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          
      - name: Build with Maven
        run: mvn package
        
      - name: Download a file
        continue-on-error: true
        uses: carlosperate/download-file-action@v1
        with:
          file-url: 'https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/.license_ignorefiles'
          file-name: '.license_ignorefiles'
          
      - name: Get defined license
        uses: octokit/request-action@v2.x
        id: get_defined_license
        with:
          route: GET /repos/{owner}/{repo}/license
          owner: octokit
          repo: request-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Check defined license
        run: "echo defined license: ${{ fromJson(steps.get_defined_license.outputs.data).license.spdx_id }}"

      - name: Start License Engine
        run: java -jar target/licenseengine-0.0.1-SNAPSHOT.jar --repo=$GITHUB_REPOSITORY --branch=$GITHUB_REF_NAME --license=${{ fromJson(steps.get_defined_license.outputs.data).license.spdx_id }}

